# durabilities of block that should be handled
blocks:
  BARREL:
    durability: 200
  CHEST:
    durability: 300
  OAK_PLANKS:
    durability: 500
  SPRUCE_PLANKS:
    durability: 500
  BIRCH_PLANKS:
    durability: 500
  JUNGLE_PLANKS:
    durability: 500
  ACACIA_PLANKS:
    durability: 500
  DARK_OAK_PLANKS:
    durability: 500
  CRIMSON_PLANKS:
    durability: 500
  WARPED_PLANKS:
    durability: 500
  STONECUTTER:
    durability: 700
  COBWEB:
    durability: 500
  STONE:
    durability: 200
  DIRT:
    durability: 500
  STRIPPED_OAK_LOG:
    durability: 2500
  STRIPPED_SPRUCE_LOG:
    durability: 2500
  STRIPPED_BIRCH_LOG:
    durability: 2500
  STRIPPED_JUNGLE_LOG:
    durability: 2500
  STRIPPED_ACACIA_LOG:
    durability: 2500
  STRIPPED_DARK_OAK_LOG:
    durability: 2500
  STRIPPED_CRIMSON_STEM:
    durability: 2500
  STRIPPED_WARPED_STEM:
    durability: 2500
  SPRUCE_DOOR:
    durability: 2000
  BIRCH_DOOR:
    durability: 2000
  JUNGLE_DOOR:
    durability: 2000
  ACACIA_DOOR:
    durability: 2000
  DARK_OAK_DOOR:
    durability: 2000
  CRIMSON_DOOR:
    durability: 2000
  WARPED_DOOR:
    durability: 2000
  OAK_TRAPDOOR:
    durability: 2000
  SPRUCE_TRAPDOOR:
    durability: 2000
  BIRCH_TRAPDOOR:
    durability: 2000
  JUNGLE_TRAPDOOR:
    durability: 2000
  ACACIA_TRAPDOOR:
    durability: 2000
  DARK_OAK_TRAPDOOR:
    durability: 2000
  CRIMSON_TRAPDOOR:
    durability: 2000
  WARPED_TRAPDOOR:
    durability: 2000
  SMOOTH_STONE_SLAB:
    durability: 2000
  SMOOTH_STONE:
    durability: 4000
  IRON_DOOR:
    durability: 7000
  IRON_TRAPDOOR:
    durability: 7000
  IRON_BLOCK:
    durability: 8000
  BRICKS:
    durability: 10000
  OBSIDIAN:
    durability: 12000
  ANCIENT_DEBRIS:
    durability: 12000
  CRYING_OBSIDIAN:
    durability: 30000

# the damage that an explosion will do to adjacent durable blocks
explosionDamage:
  ENDER_DRAGON: 500
  ENDER_CRYSTAL: 200
  WITHER: 120
  PRIMED_TNT: 100
  CREEPER: 30
  WITHER_SKULL: 5
  BED: 5
  RESPAWN_ANCHOR: 5
# modifier to the amount of damage done to tools used to mine durable blocks
# applied per durability point
toolDamageModifier: 0.2
# block repair settings
repair:
  # amount of durability restored each time a block is healed
  repairDelta: 100
  # the cost to repair a single block by the amount specified in "repairDelta"
  repairCost: 0.01
  # frequency in seconds at which blocks in each faction will be repaired
  repairFrequency: 300
# worlds in which the plugin is disabled
disabledWorlds:
  - disabledWorld