# blocks whose durability the plugin should handle
blocks:
  OAK_PLANKS:
    durability: 500
    drop: true
  SPRUCE_PLANKS:
    durability: 500
    drop: true
  BIRCH_PLANKS:
    durability: 500
    drop: true
  JUNGLE_PLANKS:
    durability: 500
    drop: true
  ACACIA_PLANKS:
    durability: 500
    drop: true
  DARK_OAK_PLANKS:
    durability: 500
    drop: true
  CRIMSON_PLANKS:
    durability: 500
    drop: true
  WARPED_PLANKS:
    durability: 500
    drop: true
  STRIPPED_OAK_LOG:
    durability: 2000
    drop: true
  STRIPPED_SPRUCE_LOG:
    durability: 2000
    drop: true
  STRIPPED_BIRCH_LOG:
    durability: 2000
    drop: true
  STRIPPED_JUNGLE_LOG:
    durability: 2000
    drop: true
  STRIPPED_ACACIA_LOG:
    durability: 2000
    drop: true
  STRIPPED_DARK_OAK_LOG:
    durability: 2000
    drop: true
  STRIPPED_CRIMSON_STEM:
    durability: 2000
    drop: true
  STRIPPED_WARPED_STEM:
    durability: 2000
    drop: true
  SPRUCE_DOOR:
    durability: 1500
    drop: true
  BIRCH_DOOR:
    durability: 1500
    drop: true
  JUNGLE_DOOR:
    durability: 1500
    drop: true
  ACACIA_DOOR:
    durability: 1500
    drop: true
  DARK_OAK_DOOR:
    durability: 1500
    drop: true
  CRIMSON_DOOR:
    durability: 1500
    drop: true
  WARPED_DOOR:
    durability: 1500
    drop: true
  SPRUCE_TRAPDOOR:
    durability: 1500
    drop: true
  BIRCH_TRAPDOOR:
    durability: 1500
    drop: true
  JUNGLE_TRAPDOOR:
    durability: 1500
    drop: true
  ACACIA_TRAPDOOR:
    durability: 1500
    drop: true
  DARK_OAK_TRAPDOOR:
    durability: 1500
    drop: true
  CRIMSON_TRAPDOOR:
    durability: 1500
    drop: true
  WARPED_TRAPDOOR:
    durability: 1500
    drop: true
  SMOOTH_STONE:
    durability: 5000
    drop: false
  BRICKS:
    durability: 10000
    drop: false
  IRON_DOOR:
    durability: 20000
    drop: false
  IRON_TRAPDOOR:
    durability: 20000
    drop: false
  IRON_BLOCK:
    durability: 30000
    drop: false
  OBSIDIAN:
    durability: 50000
    drop: false
# the power that an explosion has at its center
explosionPower: 500
# modifier to the amount of damage done to tools which you mine with
toolDamageModifier: 0.2
# worlds in which the plugin is disabled
disabledWorlds:
  - disabledWorld